# Generated by Django 4.0.3 on 2022-04-11 09:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='TemporaryExcelKeeper',
        ),
    ]
